services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ssst"
    ports:
      - 5432:5432
  redis:
    image: redis

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - db
  
  server:
    build:
      context: ./server/
    image: server:tag
    ports:
      - 8080:8080
      - 9229:9229
    depends_on:
      - db
      - redis
    volumes:
      - $HOME/Projects/ssst/server/:/usr/src/app/
  